#pragma once

/* AST enums*/

typedef enum ASTKind {
    AST_NUM,
    AST_BINOP,
    AST_UNOP,
    AST_VAR,
    AST_BOOL,
    AST_ASSIGN,
    AST_SEQ,
    AST_NULL,
    AST_IF,
    AST_FOR,
    AST_STR,
    AST_CHAR,
    AST_WHILE,
    AST_FN,
    AST_CALL,
    AST_RETURN,
    AST_IMPORT,
    AST_LIST,
    AST_RANGE,
    AST_INDEX,
    AST_CONTINUE,
    AST_BREAK,
    AST_BLOCK,
    AST_DECL
} ASTKind_t;

typedef enum DataTypes{
    I8,
    I16,
    I32,
    I64,
    I128,

    F32,
    F64,
    F128,

    UF32,
    UF64,
    UF128,

    U8,
    U16,
    U32,
    U64,
    U128,
    
    PTR,
    LIST,
    RANGE,

    BOOL,
    STRINGS,
    CHARACTER,
    VOID,
    UNKNOWN
} DataTypes_t;

typedef enum OP_kind {
    OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_MOD, OP_POW,
    OP_AND, OP_OR, OP_NOT,
    OP_EQ, OP_NEQ, OP_LT, OP_LE, OP_GT, OP_GE,
    OP_LSHIFT, OP_RSHIFT,
    OP_BITAND, OP_BITOR, OP_BITXOR, OP_BITNOT,
    OP_NEG, OP_POS,
    OP_ASSIGN, OP_PLUS_ASSIGN, OP_MINUS_ASSIGN,
    OP_MUL_ASSIGN, OP_DIV_ASSIGN, OP_MOD_ASSIGN, OP_POW_ASSIGN,
    OP_LSHIFT_ASSIGN, OP_RSHIFT_ASSIGN,
    OP_INC, OP_DEC,
    OP_ADDR, OP_DEREF,
} OP_kind_t;

/* error/warn enums*/

typedef enum errc {
    /* Lexer */
    LEX_UNKNOWN_CHAR = 1,
    LEX_INVALID_ESCAPE,
    LEX_UNCLOSED_COMMENT,

    /* Parser */
    PARSE_SYNTAX = 100,
    PARSE_MISSING_SEMI,
    PARSE_UNCLOSED_PAREN,
    PARSE_UNCLOSED_BRACE,
    PARSE_UNCLOSED_BRACKET,
    PARSE_INVALID_IMPORT,
    PARSE_IMPORT_NOT_TOP,
    PARSE_INVALID_ARRAY_SIZE,

    /* Semantic */
    SEM_VAR_UNDECL = 1001,
    SEM_VAR_TYPE_MISMATCH,
    SEM_BINOP_INVALID,
    SEM_STRING_OP_INVALID,
    SEM_CMP_NEEDS_NUM,
    SEM_LOGIC_NEEDS_BOOL,
    SEM_NUMOP_NEEDS_NUM,
    SEM_NOT_NEEDS_BOOL,
    SEM_UNARY_NEEDS_NUM,
    SEM_ASSIGN_TARGET_NOT_VAR,
    SEM_VAR_REDECL,
    SEM_ASSIGN_TYPE_MISMATCH,
    SEM_ASSIGN_IMMUTABLE,
    SEM_IF_COND_NOT_BOOL,
    SEM_FOR_INIT_INVALID,
    SEM_FOR_INIT_NOT_NUM,
    SEM_FOR_END_TYPE_MISMATCH,
    SEM_FOR_STEP_TYPE_MISMATCH,
    SEM_WHILE_COND_NOT_BOOL,
    SEM_FN_REDECL,
    SEM_DUP_PARAM,
    SEM_CALL_UNDEF_FN,
    SEM_ARGC_MISMATCH,
    SEM_ARG_TYPE_MISMATCH,
    SEM_RETURN_OUTSIDE_FN,
    SEM_RETURN_TYPE_MISMATCH,
    SEM_NUMERIC_LITERAL_OVERFLOW,
    SEM_UNKNOWN_AST = 1099,
    SEM_IMPORT_FILE_NOT_FOUND,
    SEM_LIST_SIZE_MISMATCH,
    SEM_LIST_EMPTY,
    SEM_LIST_NUM_IS_0,
    SEM_INDEX_NOT_ARRAY,
    SEM_INDEX_NOT_INT,
    SEM_INTERNAL_ERROR,
    SEM_FOR_ITERABLE_NOT_RANGE,
    SEM_FOR_ITERABLE_INVALID_TYPE,
    SEM_BREAK_OUTSIDE_LOOP,
    SEM_CONTINUE_OUTSIDE_LOOP,
    SEM_RANGE_STEP_ERROR,
    SEM_GLOBAL_VAR_IS_NOT_ASSINED_WITH_AT,

    /*LLVM ERROR*/
    INVAILD_UTF8_CHAR = 2000,
    RET_NOT_DECLARED,

    /* Runtime/Eval */
    RT_NUM_LITERAL_UNSUPPORTED = 3001,
    RT_BINOP_UNSUPPORTED,
    RT_FOR_INIT_INVALID,
    RT_FOR_STEP_ZERO,
    RT_CALL_UNDEF_FN,
    RT_ARGC_MISMATCH,
    RT_UNKNOWN_AST,
    RT_VAR_NOT_DEFINED,
    RT_VAR_TYPE_MISMATCH,
    RT_ASSIGN_TARGET_NOT_VAR,
    RT_ASSIGN_UNSUPPORTED,
    RT_DANGLING_PTR,
    RT_INDEX_OUT_OF_BOUNDS,

} errc_t;

typedef enum warnc {
    /* Semantic */
    SEM_VAR_SHADOW = 1101,
    SEM_UNUSED_VAR = 1102,
    SEM_UNUSED_FN = 1103,
    SEM_TYPE_WIDENED = 1104,
    SEM_UNKNOWN_TYPE = 1199,
} warnc_t;
